const DAY = 24 * 60 * 60 * 1000;
const base = Date.UTC(2026, 5, 7, 12, 0, 0);

function at(hour, minute = 0, dayOffset = 0) {
  return base + (dayOffset * DAY) + (hour * 60 + minute) * 60 * 1000;
}

export function createRichCaretakerScenario() {
  const eegSessionId = 1;
  const lamotrigineId = 1;
  const diazepamId = 2;

  return {
    settings: [
      { key: 'userMode', value: 'CARETAKER' },
      { key: 'personName', value: 'Alex Example' },
      { key: 'caretakerName', value: 'Morgan Example' },
      { key: 'dateOfBirth', value: '1995-04-12' },
      { key: 'emergencyContact', value: '+47 123 45 678' },
      { key: 'neurologistName', value: 'Dr. Rowan' },
      { key: 'neurologistInstitution', value: 'North Clinic' },
      { key: 'neurologistContact', value: '+47 555 11 222' },
      { key: 'medicationStartDate', value: '2026-06-01' },
      { key: 'historyPageSize', value: 10 },
      { key: 'dateFormat', value: 'ISO' },
      { key: 'timeFormat', value: '24h' },
      { key: 'durationFormat', value: 'human' },
      { key: 'language', value: 'en' },
    ],
    medications: [
      {
        id: lamotrigineId,
        uuid: 'med-lamotrigine',
        name: 'Lamotrigine',
        dose: 150,
        unit: 'mg',
        frequency: 'BD',
        isRescue: false,
        active: true,
        scheduledTimes: ['08:00', '20:00'],
        scheduledDays: [0, 1, 2, 3, 4, 5, 6],
        reminderEnabled: true,
        showInEmergency: false,
      },
      {
        id: diazepamId,
        uuid: 'med-diazepam',
        name: 'Diazepam',
        dose: 10,
        unit: 'mg',
        frequency: 'PRN',
        isRescue: true,
        active: true,
        scheduledTimes: [],
        scheduledDays: [0, 1, 2, 3, 4, 5, 6],
        reminderEnabled: false,
        showInEmergency: true,
      },
    ],
    medicationLogs: [
      {
        id: 1,
        uuid: 'log-1',
        medicationId: lamotrigineId,
        medicationUuid: 'med-lamotrigine',
        scheduledTime: '08:00',
        takenAt: at(8, 5),
        status: 'taken',
      },
      {
        id: 2,
        uuid: 'log-2',
        medicationId: lamotrigineId,
        medicationUuid: 'med-lamotrigine',
        scheduledTime: '20:00',
        takenAt: at(20, 40, -1),
        status: 'late',
        isEdited: true,
      },
      {
        id: 3,
        uuid: 'log-3',
        medicationId: diazepamId,
        medicationUuid: 'med-diazepam',
        scheduledTime: null,
        takenAt: at(9, 20, -2),
        status: 'taken',
        note: 'Rescue dose after cluster.',
      },
    ],
    events: [
      {
        id: 1,
        uuid: 'event-1',
        startTime: at(7, 42),
        date: '2026-06-07',
        time: '07:42:00',
        duration: 95,
        laps: { aura: at(7, 50), seizure: at(7, 51) },
        type: 'Focal Aware',
        isComplete: true,
        isEdited: false,
        notes: 'Quick recovery.',
        editLog: [],
        userModeAtTime: 'CARETAKER',
        isManualEntry: false,
        eegSessionId,
        eegSessionUuid: 'eeg-session-1',
        videoAttached: false,
      },
      {
        id: 2,
        uuid: 'event-2',
        startTime: at(19, 10, -1),
        date: '2026-06-06',
        time: '19:10:00',
        duration: 380,
        laps: {},
        type: 'Tonic-Clonic',
        isComplete: false,
        isEdited: false,
        notes: 'Needs additional detail.',
        editLog: [],
        userModeAtTime: 'CARETAKER',
        isManualEntry: true,
        eegSessionId: null,
        eegSessionUuid: '',
        videoAttached: true,
      },
    ],
    eegSessions: [
      {
        id: eegSessionId,
        uuid: 'eeg-session-1',
        startTime: at(6, 0),
        plannedEndTime: at(6, 0, 1),
        actualEndTime: null,
        durationPreset: '24h',
        customHours: null,
        title: 'Home EEG Session',
        notes: 'Home observation with routine activities.',
        status: 'ACTIVE',
        createdAt: at(6, 0),
        updatedAt: at(7, 45),
      },
    ],
    eegActivities: [
      {
        id: 1,
        uuid: 'eeg-activity-1',
        sessionId: eegSessionId,
        kind: 'ACTIVITY',
        activityLabel: 'Reading',
        customActivityText: 'Quiet reading on sofa',
        moodLabel: 'Calm',
        notes: 'No symptoms noted.',
        startTime: at(6, 15),
        endTime: at(6, 45),
        durationSec: 1800,
        linkedEventId: null,
        linkedEventUuid: '',
        isEdited: false,
        editLog: [],
        createdAt: at(6, 15),
        updatedAt: at(6, 45),
      },
      {
        id: 2,
        uuid: 'eeg-activity-2',
        sessionId: eegSessionId,
        kind: 'SEIZURE_REFERENCE',
        activityLabel: 'Focal Aware',
        customActivityText: '',
        moodLabel: '',
        notes: 'Linked seizure during EEG.',
        startTime: at(7, 42),
        endTime: at(7, 43),
        durationSec: 95,
        linkedEventId: 1,
        linkedEventUuid: 'event-1',
        isEdited: false,
        editLog: [],
        createdAt: at(7, 43),
        updatedAt: at(7, 43),
      },
    ],
  };
}
